services:
  openrss:
    image: registry.williamloree.fr/openrss:latest
    container_name: openrss-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - openrss-data:/app/data
    restart: unless-stopped
    networks:
      - openrss-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  openrss-network:
    driver: bridge

volumes:
  openrss-data:
    driver: local
