services:
  openrss:
    image: registry.williamloree.fr/openrss:latest
    container_name: openrss-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - openrss-network

networks:
  openrss-network:
    driver: bridge
